### ISSUE TITLE
Chart installation failed

### ISSUE THREAD

**Issue by mojabyte** [emqx/emqx-chart#9]
Helm install chart failed with error: helm no matches for kind "StatefulSet" in version "apps/v1beta1"
with helm v2.14.3 & Kubernetes v1.16.0

**Comment by qadet123** [comment]
According to [this PR](https://github.com/kubernetes/kubernetes/pull/70672) ,you should change the [apiVersion: apps/v1beta1](https://github.com/emqx/emqx-chart/blob/8383005e3e3701e8827abc5df1f14a0fd508661d/charts/emqx/templates/StatefulSet.yaml#L1)  to "apps/v1".
In fact any case with k8s version >= 1.9 should use apps/v1 instead of  apps/v1beta1, apps/v1beta2, extensions/v1beta1
